      - name: Build Docker Image
        run: |
          docker build -t yassine/springboot-app \
          --build-arg JAR_FILE=springboot/app/target/*.jar \
          -f springboot/app/Dockerfile .

